### ISSUE TITLE
Line duplication in kef_connector.py (0.6)

### ISSUE THREAD

**Issue by renebouwmeester** [N0ciple/pykefcontrol#1]
Lines 7 & 8 are duplicated:

7 class KefConnector:
8 class KefConnector:

Resulting in indentation error. Removing one solves it.

**Comment by N0ciple** [comment]
Really sorry about this typo !
version 0.6.1 is already pushed on Pypi, and it fixes the issue as well as adding new feature (I'm actually edditing the README).
Please feel free to reopen if version 0.6.1 does not correct the bug (but it should!)
