### ISSUE TITLE
I've built a Web App to control my LSX II

### ISSUE THREAD

**Issue by dragosdydy** [N0ciple/pykefcontrol#4]
I wasn't sure where to post this, feel free to close it. Just wanted to say thank you for building this. I am using the speakers a lot connected to my PC and I hate the volume control of the remote control. 

I've used this library to build a simple web app that allows me to select the source, turn them on/off and control the volume (with precision).

See screenshots attached
![image](https://github.com/N0ciple/pykefcontrol/assets/8168524/1fdb75fc-2dee-4316-95b0-13a621919366)
![image](https://github.com/N0ciple/pykefcontrol/assets/8168524/ac1c792e-e0de-475a-bae2-38c231785e4f)

Thank you so much.

**Comment by N0ciple** [comment]
Thanks for your kind words.
You app looks really nice ! Do you have any plans of releasing it or publishing the code on github ?
